name: payment_gateway

services:

  db:
    image: "postgres:16-alpine"
    environment:
      - POSTGRES_USER=payment_gateway
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=payment_gateway
    ports:
      - "5432"
    volumes:
      - dbdata:/var/lib/postgresql/data:delegated
    networks:
      - payment_gateway

  db-test:
    image: "postgres:16-alpine"
    environment:
      - POSTGRES_USER=payment_gateway
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=payment_gateway_test
    ports:
      - "5433:5432"
    tmpfs:
      - /var/lib/postgresql/data
    networks:
      - payment_gateway

  broker:
    image: "rabbitmq:alpine"
    networks:
      - payment_gateway

  result:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    networks:
      - payment_gateway

  frontend:
    build:
      dockerfile: frontend/Dockerfile
      context: .
    volumes:
      - .:/app/
      - /app/node_modules
    ports:
      - "3000:3000"
    networks:
      - payment_gateway

  backend:
    build:
      dockerfile: backend/Dockerfile
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./:/home/user/app/
    env_file: backend/.env
    depends_on:
      - db
      - broker
      - result
      - frontend
    networks:
      - payment_gateway

  celery:
    build:
      dockerfile: backend/Dockerfile
      context: .
    command: celery --app=payment_gateway worker --loglevel=info
    volumes:
      - ./:/home/user/app/
    env_file: backend/.env
    depends_on:
      - db
      - broker
      - result
    networks:
      - payment_gateway

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - payment_gateway

volumes:
  dbdata:
    name: "payment_gateway_dbdata"
    external: true

networks:
  payment_gateway:
    driver: bridge