// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { ApiPaymentsCreateData, ApiPaymentsCreateResponses, ApiPaymentsReplayCreateData, ApiPaymentsReplayCreateResponses, ApiPaymentsRetrieveData, ApiPaymentsRetrieveResponses, ApiRestRestCheckRetrieveData, ApiRestRestCheckRetrieveResponses, ApiUsersCreateData, ApiUsersCreateResponses, ApiUsersDestroyData, ApiUsersDestroyResponses, ApiUsersListData, ApiUsersListResponses, ApiUsersPartialUpdateData, ApiUsersPartialUpdateResponses, ApiUsersRetrieveData, ApiUsersRetrieveResponses, ApiUsersUpdateData, ApiUsersUpdateResponses, ProcessorChargeCreateData, ProcessorChargeCreateResponses, ProcessorTokenizeCreateData, ProcessorTokenizeCreateResponses, WebhooksProcessorCreateData, WebhooksProcessorCreateResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Create a payment with idempotency support.
 */
export const apiPaymentsCreate = <ThrowOnError extends boolean = false>(options: Options<ApiPaymentsCreateData, ThrowOnError>) => {
    return (options.client ?? client).post<ApiPaymentsCreateResponses, unknown, ThrowOnError>({
        responseType: 'json',
        security: [
            {
                in: 'cookie',
                name: 'sessionid',
                type: 'apiKey'
            }
        ],
        url: '/api/payments',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Get payment status and ledger history.
 */
export const apiPaymentsRetrieve = <ThrowOnError extends boolean = false>(options: Options<ApiPaymentsRetrieveData, ThrowOnError>) => {
    return (options.client ?? client).get<ApiPaymentsRetrieveResponses, unknown, ThrowOnError>({
        responseType: 'json',
        security: [
            {
                in: 'cookie',
                name: 'sessionid',
                type: 'apiKey'
            }
        ],
        url: '/api/payments/{payment_id}',
        ...options
    });
};

/**
 * Admin-only: re-request a stuck payment's result from the processor.
 */
export const apiPaymentsReplayCreate = <ThrowOnError extends boolean = false>(options: Options<ApiPaymentsReplayCreateData, ThrowOnError>) => {
    return (options.client ?? client).post<ApiPaymentsReplayCreateResponses, unknown, ThrowOnError>({
        responseType: 'json',
        security: [
            {
                in: 'cookie',
                name: 'sessionid',
                type: 'apiKey'
            }
        ],
        url: '/api/payments/{payment_id}/replay',
        ...options
    });
};

/**
 * Check REST API
 *
 * This endpoint checks if the REST API is working.
 */
export const apiRestRestCheckRetrieve = <ThrowOnError extends boolean = false>(options?: Options<ApiRestRestCheckRetrieveData, ThrowOnError>) => {
    return (options?.client ?? client).get<ApiRestRestCheckRetrieveResponses, unknown, ThrowOnError>({
        responseType: 'json',
        security: [
            {
                in: 'cookie',
                name: 'sessionid',
                type: 'apiKey'
            }
        ],
        url: '/api/rest/rest-check/',
        ...options
    });
};

export const apiUsersList = <ThrowOnError extends boolean = false>(options?: Options<ApiUsersListData, ThrowOnError>) => {
    return (options?.client ?? client).get<ApiUsersListResponses, unknown, ThrowOnError>({
        responseType: 'json',
        security: [
            {
                in: 'cookie',
                name: 'sessionid',
                type: 'apiKey'
            }
        ],
        url: '/api/users/',
        ...options
    });
};

export const apiUsersCreate = <ThrowOnError extends boolean = false>(options: Options<ApiUsersCreateData, ThrowOnError>) => {
    return (options.client ?? client).post<ApiUsersCreateResponses, unknown, ThrowOnError>({
        responseType: 'json',
        security: [
            {
                in: 'cookie',
                name: 'sessionid',
                type: 'apiKey'
            }
        ],
        url: '/api/users/',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

export const apiUsersDestroy = <ThrowOnError extends boolean = false>(options: Options<ApiUsersDestroyData, ThrowOnError>) => {
    return (options.client ?? client).delete<ApiUsersDestroyResponses, unknown, ThrowOnError>({
        security: [
            {
                in: 'cookie',
                name: 'sessionid',
                type: 'apiKey'
            }
        ],
        url: '/api/users/{id}/',
        ...options
    });
};

export const apiUsersRetrieve = <ThrowOnError extends boolean = false>(options: Options<ApiUsersRetrieveData, ThrowOnError>) => {
    return (options.client ?? client).get<ApiUsersRetrieveResponses, unknown, ThrowOnError>({
        responseType: 'json',
        security: [
            {
                in: 'cookie',
                name: 'sessionid',
                type: 'apiKey'
            }
        ],
        url: '/api/users/{id}/',
        ...options
    });
};

export const apiUsersPartialUpdate = <ThrowOnError extends boolean = false>(options: Options<ApiUsersPartialUpdateData, ThrowOnError>) => {
    return (options.client ?? client).patch<ApiUsersPartialUpdateResponses, unknown, ThrowOnError>({
        responseType: 'json',
        security: [
            {
                in: 'cookie',
                name: 'sessionid',
                type: 'apiKey'
            }
        ],
        url: '/api/users/{id}/',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

export const apiUsersUpdate = <ThrowOnError extends boolean = false>(options: Options<ApiUsersUpdateData, ThrowOnError>) => {
    return (options.client ?? client).put<ApiUsersUpdateResponses, unknown, ThrowOnError>({
        responseType: 'json',
        security: [
            {
                in: 'cookie',
                name: 'sessionid',
                type: 'apiKey'
            }
        ],
        url: '/api/users/{id}/',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Charge a tokenized payment method.
 *
 * Returns a processor_reference. The final result arrives via webhook.
 */
export const processorChargeCreate = <ThrowOnError extends boolean = false>(options: Options<ProcessorChargeCreateData, ThrowOnError>) => {
    return (options.client ?? client).post<ProcessorChargeCreateResponses, unknown, ThrowOnError>({
        responseType: 'json',
        security: [
            {
                in: 'cookie',
                name: 'sessionid',
                type: 'apiKey'
            }
        ],
        url: '/processor/charge',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Tokenize card or bank details.
 *
 * Accepts card details (number, expiry, CVV) or bank details
 * (account_number, routing_number) and returns a token.
 */
export const processorTokenizeCreate = <ThrowOnError extends boolean = false>(options: Options<ProcessorTokenizeCreateData, ThrowOnError>) => {
    return (options.client ?? client).post<ProcessorTokenizeCreateResponses, unknown, ThrowOnError>({
        responseType: 'json',
        security: [
            {
                in: 'cookie',
                name: 'sessionid',
                type: 'apiKey'
            }
        ],
        url: '/processor/tokenize',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Receive and process processor webhooks.
 */
export const webhooksProcessorCreate = <ThrowOnError extends boolean = false>(options?: Options<WebhooksProcessorCreateData, ThrowOnError>) => {
    return (options?.client ?? client).post<WebhooksProcessorCreateResponses, unknown, ThrowOnError>({
        security: [
            {
                in: 'cookie',
                name: 'sessionid',
                type: 'apiKey'
            }
        ],
        url: '/webhooks/processor',
        ...options
    });
};
