// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: `${string}://${string}` | (string & {});
};

export type Charge = {
    token: string;
    amount: number;
    currency?: string;
};

export type LedgerEntry = {
    readonly id: string;
    event_id: string;
    status: string;
    failure_code?: string | null;
    occurred_at: string;
    readonly created: string;
};

export type Message = {
    message: string;
};

/**
 * * `card` - card
 * * `bank` - bank
 */
export type MethodEnum = 'card' | 'bank';

export type PaginatedUserList = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<User>;
};

export type PatchedUser = {
    readonly id?: number;
    email?: string;
    /**
     * Designates whether this user should be treated as active. Unselect this instead of deleting accounts.
     */
    is_active?: boolean;
    /**
     * Designates whether the user can log into this admin site.
     */
    is_staff?: boolean;
    /**
     * Superuser status
     *
     * Designates that this user has all permissions without explicitly assigning them.
     */
    is_superuser?: boolean;
    readonly created?: string;
    readonly modified?: string;
    last_login?: string | null;
};

export type Payment = {
    readonly id: string;
    /**
     * Amount in minor units
     */
    amount: number;
    currency?: string;
    payment_token: string;
    status?: StatusEnum;
    failure_code?: string | null;
    processor_reference?: string | null;
    readonly ledger: Array<LedgerEntry>;
    readonly created: string;
    readonly modified: string;
};

export type PaymentCreate = {
    amount: number;
    currency?: string;
    payment_token: string;
};

/**
 * * `pending` - Pending
 * * `succeeded` - Succeeded
 * * `failed` - Failed
 */
export type StatusEnum = 'pending' | 'succeeded' | 'failed';

export type Tokenize = {
    method: MethodEnum;
    card_number?: string;
    expiry?: string;
    cvv?: string;
    account_number?: string;
    routing_number?: string;
};

export type User = {
    readonly id: number;
    email: string;
    /**
     * Designates whether this user should be treated as active. Unselect this instead of deleting accounts.
     */
    is_active?: boolean;
    /**
     * Designates whether the user can log into this admin site.
     */
    is_staff?: boolean;
    /**
     * Superuser status
     *
     * Designates that this user has all permissions without explicitly assigning them.
     */
    is_superuser?: boolean;
    readonly created: string;
    readonly modified: string;
    last_login?: string | null;
};

export type LedgerEntryWritable = {
    event_id: string;
    status: string;
    failure_code?: string | null;
    occurred_at: string;
};

export type PatchedUserWritable = {
    email?: string;
    /**
     * Designates whether this user should be treated as active. Unselect this instead of deleting accounts.
     */
    is_active?: boolean;
    /**
     * Designates whether the user can log into this admin site.
     */
    is_staff?: boolean;
    /**
     * Superuser status
     *
     * Designates that this user has all permissions without explicitly assigning them.
     */
    is_superuser?: boolean;
    last_login?: string | null;
};

export type PaymentWritable = {
    /**
     * Amount in minor units
     */
    amount: number;
    currency?: string;
    payment_token: string;
    status?: StatusEnum;
    failure_code?: string | null;
    processor_reference?: string | null;
};

export type UserWritable = {
    email: string;
    /**
     * Designates whether this user should be treated as active. Unselect this instead of deleting accounts.
     */
    is_active?: boolean;
    /**
     * Designates whether the user can log into this admin site.
     */
    is_staff?: boolean;
    /**
     * Superuser status
     *
     * Designates that this user has all permissions without explicitly assigning them.
     */
    is_superuser?: boolean;
    last_login?: string | null;
};

export type ApiPaymentsCreateData = {
    body: PaymentCreate;
    headers: {
        /**
         * Unique key to safely retry this request without creating duplicate payments.
         */
        'Idempotency-Key': string;
    };
    path?: never;
    query?: never;
    url: '/api/payments';
};

export type ApiPaymentsCreateResponses = {
    200: Payment;
};

export type ApiPaymentsCreateResponse = ApiPaymentsCreateResponses[keyof ApiPaymentsCreateResponses];

export type ApiPaymentsRetrieveData = {
    body?: never;
    path: {
        payment_id: string;
    };
    query?: never;
    url: '/api/payments/{payment_id}';
};

export type ApiPaymentsRetrieveResponses = {
    200: Payment;
};

export type ApiPaymentsRetrieveResponse = ApiPaymentsRetrieveResponses[keyof ApiPaymentsRetrieveResponses];

export type ApiPaymentsReplayCreateData = {
    body?: never;
    path: {
        payment_id: string;
    };
    query?: never;
    url: '/api/payments/{payment_id}/replay';
};

export type ApiPaymentsReplayCreateResponses = {
    200: Payment;
};

export type ApiPaymentsReplayCreateResponse = ApiPaymentsReplayCreateResponses[keyof ApiPaymentsReplayCreateResponses];

export type ApiRestRestCheckRetrieveData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/rest/rest-check/';
};

export type ApiRestRestCheckRetrieveResponses = {
    200: Message;
};

export type ApiRestRestCheckRetrieveResponse = ApiRestRestCheckRetrieveResponses[keyof ApiRestRestCheckRetrieveResponses];

export type ApiUsersListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Number of results to return per page.
         */
        limit?: number;
        /**
         * The initial index from which to return the results.
         */
        offset?: number;
    };
    url: '/api/users/';
};

export type ApiUsersListResponses = {
    200: PaginatedUserList;
};

export type ApiUsersListResponse = ApiUsersListResponses[keyof ApiUsersListResponses];

export type ApiUsersCreateData = {
    body: UserWritable;
    path?: never;
    query?: never;
    url: '/api/users/';
};

export type ApiUsersCreateResponses = {
    201: User;
};

export type ApiUsersCreateResponse = ApiUsersCreateResponses[keyof ApiUsersCreateResponses];

export type ApiUsersDestroyData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this user.
         */
        id: number;
    };
    query?: never;
    url: '/api/users/{id}/';
};

export type ApiUsersDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type ApiUsersDestroyResponse = ApiUsersDestroyResponses[keyof ApiUsersDestroyResponses];

export type ApiUsersRetrieveData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this user.
         */
        id: number;
    };
    query?: never;
    url: '/api/users/{id}/';
};

export type ApiUsersRetrieveResponses = {
    200: User;
};

export type ApiUsersRetrieveResponse = ApiUsersRetrieveResponses[keyof ApiUsersRetrieveResponses];

export type ApiUsersPartialUpdateData = {
    body?: PatchedUserWritable;
    path: {
        /**
         * A unique integer value identifying this user.
         */
        id: number;
    };
    query?: never;
    url: '/api/users/{id}/';
};

export type ApiUsersPartialUpdateResponses = {
    200: User;
};

export type ApiUsersPartialUpdateResponse = ApiUsersPartialUpdateResponses[keyof ApiUsersPartialUpdateResponses];

export type ApiUsersUpdateData = {
    body: UserWritable;
    path: {
        /**
         * A unique integer value identifying this user.
         */
        id: number;
    };
    query?: never;
    url: '/api/users/{id}/';
};

export type ApiUsersUpdateResponses = {
    200: User;
};

export type ApiUsersUpdateResponse = ApiUsersUpdateResponses[keyof ApiUsersUpdateResponses];

export type ProcessorChargeCreateData = {
    body: Charge;
    path?: never;
    query?: never;
    url: '/processor/charge';
};

export type ProcessorChargeCreateResponses = {
    200: {
        [key: string]: unknown;
    };
};

export type ProcessorChargeCreateResponse = ProcessorChargeCreateResponses[keyof ProcessorChargeCreateResponses];

export type ProcessorTokenizeCreateData = {
    body: Tokenize;
    path?: never;
    query?: never;
    url: '/processor/tokenize';
};

export type ProcessorTokenizeCreateResponses = {
    200: {
        [key: string]: unknown;
    };
};

export type ProcessorTokenizeCreateResponse = ProcessorTokenizeCreateResponses[keyof ProcessorTokenizeCreateResponses];

export type WebhooksProcessorCreateData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/webhooks/processor';
};

export type WebhooksProcessorCreateResponses = {
    /**
     * No response body
     */
    200: unknown;
};
