# Generated by Django 6.0.8 on 2026-09-30 18:12

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idempotency_key', models.CharField(blank=True, max_length=255, null=True, verbose_name='idempotency key')),
                ('idempotency_body_hash', models.CharField(blank=True, max_length=64, null=True, verbose_name='idempotency body hash')),
                ('amount', models.PositiveIntegerField(verbose_name='amount in minor units')),
                ('currency', models.CharField(default='USD', max_length=3, verbose_name='currency')),
                ('payment_token', models.CharField(max_length=255, verbose_name='payment token')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='pending', max_length=10, verbose_name='status')),
                ('failure_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='failure code')),
                ('processor_reference', models.CharField(blank=True, max_length=255, null=True, verbose_name='processor reference')),
            ],
            options={
                'verbose_name': 'payment',
                'verbose_name_plural': 'payments',
                'constraints': [models.UniqueConstraint(fields=('idempotency_key', 'idempotency_body_hash'), name='unique_idempotency_key_body')],
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_id', models.CharField(max_length=255, verbose_name='event ID')),
                ('status', models.CharField(max_length=10, verbose_name='status')),
                ('failure_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='failure code')),
                ('occurred_at', models.DateTimeField(verbose_name='occurred at')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='payments.payment', verbose_name='payment')),
            ],
            options={
                'verbose_name': 'ledger entry',
                'verbose_name_plural': 'ledger entries',
                'ordering': ['occurred_at', 'created'],
                'unique_together': {('payment', 'event_id')},
            },
        ),
    ]
