# Generated by Django 5.2.17 on 2026-10-04 17:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledgerentry',
            name='status',
            field=models.CharField(max_length=16, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('created', 'Created'), ('authorized', 'Authorized'), ('captured', 'Captured'), ('settled', 'Settled'), ('failed', 'Failed')], default='pending', max_length=16, verbose_name='status'),
        ),
        migrations.CreateModel(
            name='OutboxEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=64, verbose_name='event type')),
                ('payload', models.JSONField(verbose_name='payload')),
                ('delivered', models.BooleanField(db_index=True, default=False, verbose_name='delivered')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outbox_events', to='payments.payment', verbose_name='payment')),
            ],
            options={
                'verbose_name': 'outbox event',
                'verbose_name_plural': 'outbox events',
                'ordering': ['created'],
            },
        ),
    ]
