# Generated by Django 5.2.17 on 2026-10-04 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_ledgerentry_status_alter_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='customer_email',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='customer email'),
        ),
    ]
