# Generated by Django 6.0.8 on 2026-09-30 17:48

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=255, unique=True, verbose_name='token')),
                ('method', models.CharField(choices=[('card', 'Card'), ('bank', 'Bank')], max_length=10, verbose_name='method')),
                ('last4', models.CharField(max_length=4, verbose_name='last4')),
                ('brand_or_bank_type', models.CharField(max_length=50, verbose_name='brand_or_bank_type')),
            ],
            options={
                'verbose_name': 'payment method',
                'verbose_name_plural': 'payment methods',
            },
        ),
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('processor_reference', models.CharField(max_length=255, unique=True, verbose_name='processor reference')),
                ('amount', models.PositiveIntegerField(verbose_name='amount in minor units')),
                ('currency', models.CharField(default='USD', max_length=3, verbose_name='currency')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='pending', max_length=10, verbose_name='status')),
                ('failure_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='failure code')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='charges', to='mock_processor.paymentmethod', verbose_name='payment method')),
            ],
            options={
                'verbose_name': 'charge',
                'verbose_name_plural': 'charges',
            },
        ),
    ]
